apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-toolkit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-toolkit
  template:
    metadata:
      labels:
        app: devops-toolkit
    spec:
      containers:
      - name: toolkit
        image: devops-toolkit:v2
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
